name: CI
on:
  - workflow_dispatch
  - push
  - pull_request

jobs:
  build_and_deploy:
    env:
      BASE_VERSION: 3.99.0
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cd src/Nethereum.JsonRpc.TcpClient
          dotnet build Nethereum.JsonRpc.TcpClient.fsproj --property:Configuration=Release
