name: .NET Framework

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
        platform: [Any CPU]
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore nuget packages
      run: msbuild 'Nethereum.sln' /p:configuration=${{ matrix.configuration }} /p:platform='${{ matrix.platform }}' /t:restore
      
    - name: Build solution
      run: msbuild 'Nethereum.sln' /p:configuration=${{ matrix.configuration }} /p:platform='${{ matrix.platform }}'
