name: .NET
on: [ push, pull_request ]

jobs:
  build_and_deploy:
    env:
      BASE_VERSION: 0.96.0
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Package
        run: |
          cd src/Nethereum
          dotnet build Nethereum.csproj -p:Configuration=Release
      - name: Upload
        run: |
          cd src/Nethereum
          git clone https://github.com/nblockchain/fsx
          dotnet fsi fsx/Tools/nugetPush.fsx $BASE_VERSION ${{secrets.NUGET_API_KEY}}
