name: .NET
on: [ push, pull_request ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Build Nethereum
        run: dotnet pack ./src/Nethereum/Nethereum.csproj