name: .NET
on: [ push ]

jobs:
  build_and_deploy:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cd src
        ./nuget.bat
    - name: list packages
      run: ls packages
    - name: Publish NuGet website
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/')) && env.NUGET_API_KEY != null
      run: |
        dotnet nuget push packages/* --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json