name: CI
on:
  - push 
  - pull_request 

jobs:
  build_and_deploy:
    env:
      BASE_VERSION: 3.99.0
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: |
          cd src/Nethereum
          dotnet build Nethereum.csproj --property:Configuration=Release
      - name: Package and upload
        run: |
          cd src/Nethereum
          git clone https://github.com/nblockchain/fsx
          dotnet fsi fsx/Tools/nugetPush.fsx $BASE_VERSION ${{secrets.NUGET_API_KEY}}
